### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by marconi** [vmware-archive/salt-ci#4]
Hey guys,

Is there a documentation somewhere to help get started on to use salt-ci?

**Comment by s0undt3ch** [comment]
@marconi, first of all, **Thank You** for the early interest! Just makes us want to do more and faster...

Now, your question, `salt-ci` is still in it's early stages.
According to SaltStack versioning convention, the first functional release should be `0.6.0`. If it requires "more work", maybe start at `0.5.0`.

`salt-ci` is still in about 0.1.0 :smiley: 

But I'll keep you posted!

**Comment by marconi** [comment]
aw haha really want a Python based CI and already love SaltStack so this should be a perfect fit. 

Thanks for fast reply and looking forward. :+1:

**Comment by brejoc** [comment]
:+1: for this! :)

**Comment by rallytime** [comment]
This repo is deprecated and archived. Therefore, this issue is now closed. Thank you.
