### ISSUE TITLE
Please publish the great overview (and where you could use some more hands)

### ISSUE THREAD

**Issue by brejoc** [vmware-archive/salt-ci#5]
I'm really thrilled to see that you are indeed working on a CI tool based on salt and python. I know it's in a very early stage – but it would be cool, if you could publish your vision for salt-ci, what things you'd like to accomplish and where you could need some more help in planning or coding, so that others that are interested know where contribution makes sense.

**Comment by techdragon** [comment]
Yeah id love to have an idea of where this is 'designed' to go.

**Comment by brejoc** [comment]
I'm closing this, since this seems to be dead.

**Comment by s0undt3ch** [comment]
It will happen, but yeah, not in the immediate future.... :disappointed:
