### ISSUE TITLE
State of the Project

### ISSUE THREAD

**Issue by guettli** [vmware-archive/salt-ci#6]
Hi,

there was no update since three years. Please tell interested users what is going on. 

Do you have a hint which project is more active?

**Comment by s0undt3ch** [comment]
The idea is still very present and we still want to create salt-ci, but this repo proved to be the wrong approach.

Over the years we've learned what we want and how we want salt-ci to do, but right now we're just lacking the required free time to work on it.

**Comment by guettli** [comment]
Maybe there is time to update the reademe? Please explain what you learned. I am (and I guess more people are) are interested.

**Comment by rallytime** [comment]
This repo is deprecated and archived. Therefore, this issue is now closed. Thank you.
